use("bus_tracker");

// Delete what was created previously to avoid duplicates
db.stations.drop();
db.lines.drop();

const stationNames = [
      "teilor",
      "soporului",
      "campina nord",
      "depou tram est",
      "campina nord",
      "pinului",
      "dunarii nord",
      "streiului",
      "complex dunarii nord",
      "statia muresului",
      "picasso",
      "l. matis",
      "luminii",
      "giratie drum faget",
      "e. ionesco",
      "n. steinhardt",
      "v. stoica",
      "scoala s. barnutiu",
      "intre lacuri",
      "complex dunarii sud",
      "tulcea",
      "dunarii sud",
      "harghita",
      "jiului",
      "soporului nord",
      "soporului sud",
      "tribunal",
      "rubin patitia",
      "simion barnutiu",
      "biblioteca judeteana",
      "artarului",
      "colina",
      "slanic",
      "varianta manastur",
      "frunzisului",
      "cocosul de aur",
      "frunzisului vest",
      "varianta zorilor sud",
      "eugen lovinescu vest",
      "grigore antipa vest",
      "hotel stil vest",
      "dianei vest",
      "d. d. rosca vest",
      "meteor",
      "c-tin. noica",
      "centrul medical",
      "pmv flip",
      "biserica campului",
      "grigore antipa est",
      "eugen lovinescu est",
      "balea est",
      "intermediara est",
      "pometului est",
      "piata garii vest",
      "terra est",
      "cluj due est",
      "electrogroup",
      "w. a. mozart",
      "calea turzii",
      "vila tusa",
      "d. d. rosca est",
      "dianei est",
      "hotel stil est",
      "scoala est",
      "ias est",
      "pod est",
      "drum feiurd est",
      "podul fetei est",
      "bis. greco catolica est",
      "senina sud",
      "dragos voda sud",
      "vrancea",
      "calugareni sud",
      "piata garii noi",
      "creic",
      "catun vest",
      "cluj due vest",
      "terra vest",
      "trambitasului",
      "calugareni nord",
      "spataru milescu",
      "dragos voda nord",
      "senina nord",
      "valea chintaului",
      "bis. greco catolica vest",
      "podul fetei vest",
      "drum feiurd vest",
      "pod vest",
      "ias vest",
      "scoala vest",
      "pometului vest",
      "intermediara vest",
      "vanatorului",
      "gruia",
      "baia mare",
      "emil racovita nord",
      "arena cfr nord",
      "radauti nord",
      "tiberiu brediceanu",
      "bariera cfr nord",
      "tetarom",
      "energobit nord",
      "timisului sud",
      "tetarom vest",
      "energobit sud",
      "bariera cfr sud",
      "vasile carlova",
      "radauti sud",
      "stadionul cfr",
      "crisan",
      "campina sud",
      "plevnei sud",
      "cet",
      "timisului",
      "branului sud",
      "infratirii sud",
      "pintea viteazul sud",
      "barc i",
      "parcul farmec",
      "depou vest",
      "depou est",
      "baita",
      "parcul feroviarilor",
      "blanarilor",
      "spitalul de recuperare nord",
      "spitalul de recuperare sud",
      "piata mihai viteazul",
      "i. ionescu",
      "frumoasa",
      "morii",
      "infratirii nord",
      "rodnei",
      "blajului",
      "broda",
      "plevnei nord",
      "campina nord",
      "piata oser",
      "pmv 2",
      "disp. alverna",
      "albac",
      "baisoara",
      "piata garii nord",
      "giordano bruno",
      "fagaras",
      "livezeni",
      "t. vladimirescu nord",
      "valea seaca",
      "cartier baciu",
      "fabrica de paine nord",
      "cora sud",
      "chios",
      "giuseppe garibaldi",
      "hotel radinsson blu",
      "scoala horea",
      "pmv 1",
      "napolact",
      "fabrica de paine sud",
      "calea baciului",
      "t. vladimirescu sud",
      "soarelui",
      "trandafirilor",
      "autogara",
      "b-dul 1 decembrie 1918",
      "roata faget",
      "henri barbusse pl.",
      "bucuresti",
      "farmec",
      "p-ta abator",
      "henri barbusse",
      "roata faget pl",
      "budum",
      "depou tram sud",
      "dragalina sud",
      "piata 14 iulie sud",
      "hotel napoca",
      "cora nord",
      "politia est",
      "radio romania cluj",
      "petuniei",
      "iancu de hunedoara",
      "giuseppe garibaldi 4-6",
      "piata 14 iulie nord",
      "emerson",
      "depou tram nord",
      "grupul scolar cfr est",
      "gheorghe asachi",
      "iris sud",
      "dacia",
      "dragalina nord",
      "octavian goga",
      "george enescu",
      "alexandru vlahuta",
      "buzau",
      "miraslau",
      "fantanele",
      "disp. grigorescu",
      "iris nord",
      "puietilor",
      "vivo! cluj-napoca",
      "polus center",
      "nodul nord",
      "i. p. voitesti nord",
      "disp. ers cug",
      "disp. unirii",
      "colegiul pedagogic",
      "iulius mall est",
      "campus universitar est",
      "spitalul boli infectioase",
      "v. babes",
      "ion creanga",
      "hasdeu",
      "c. porumbescu",
      "boli infectioase",
      "opera",
      "piata i. agarbiceanu vest",
      "drapelului vest",
      "becas vest",
      "fagului",
      "trifoiului nord",
      "vitacom nord",
      "compl. tempus nord",
      "hexagon",
      "drum faget",
      "dacia service",
      "compexit",
      "compl. tempus sud",
      "vitacom sud",
      "trifoiului sud",
      "becas est",
      "drapelului est",
      "piata i. agarbiceanu est",
      "andrei muresanu est",
      "balea vest",
      "dimitrie gusti",
      "e. quinet vest",
      "sere usamv sud",
      "antim ivireanul",
      "violetelor",
      "voievodul glad vest",
      "voievodul menumorut vest",
      "biserica borhanci vest",
      "biserica borhanci est",
      "voievodul menumorut est",
      "voievodul glad est",
      "theodor pallady",
      "borhanciului",
      "sere usamv nord",
      "e. quinet sud",
      "e. quinet nord",
      "scoala edmund nicolau",
      "a.n.l.",
      "gradinita mehedinti",
      "piata cipariu sud",
      "c-tin. brancoveanu vest",
      "malinului vest",
      "alverna vest",
      "antonio gaudi nord",
      "statia nordului vest",
      "uranus vest",
      "romul ladea vest",
      "dimitrie onciul vest",
      "veseliei",
      "dimitrie onciul est",
      "romul ladea est",
      "uranus est",
      "statia nordului est",
      "antonio gaudi sud",
      "alverna est",
      "malinului est",
      "c-tin. brancoveanu est",
      "posada",
      "maresal al. averescu",
      "taberei",
      "calea floresti",
      "academia de muzica",
      "bucium",
      "ciobanului",
      "piata flora",
      "dorobantilor",
      "campus universitar vest",
      "iulius mall vest",
      "valeriu bologa",
      "fabricii",
      "selgros",
      "u.m. someseni",
      "dealul borzas",
      "platanilor",
      "henri coanda",
      "halta dezmir",
      "piata agro",
      "disp. clabucet",
      "branului",
      "agro transilvania",
      "halta agro",
      "r.a.d.p",
      "posta romana",
      "gara someseni",
      "mentenantei",
      "bai someseni",
      "aiudului",
      "scoala someseni",
      "orastie",
      "ambient",
      "mos ion roata",
      "traian vuia sud",
      "aeroport sud",
      "cantonului",
      "electromontaj sud",
      "disp. ira",
      "lukoil traian vuia",
      "electromontaj nord",
      "aviatia utilitara",
      "aeroport nord",
      "traian vuia nord",
      "planoarelor",
      "vlad tepes",
      "camin someseni",
      "snagov nord",
      "borsec nord",
      "bistritei",
      "septimiu albini nord",
      "piata garii",
      "i. p. voitesti sud",
      "traian",
      "closca",
      "piata cipariu est",
      "septimiu albini sud",
      "nicolae titulescu",
      "herculane",
      "borsec sud",
      "piata garii sud",
      "piata garii",
      "snagov sud",
      "pod traian",
      "memorandumului nord",
      "spitalul de copii",
      "fabrica de bere",
      "gradini manastur",
      "ion mester",
      "peana",
      "garbau",
      "piata 1 mai",
      "ploiesti",
      "primaverii",
      "minerva",
      "izlazului",
      "calea manastur",
      "agronomia",
      "calea motilor",
      "memorandumului sud",
      "victoria",
      "voronet 40",
      "oleandrului 32",
      "sieta",
      "piata cipariu nord",
      "piata avram iancu",
      "piata mihai viteazul est",
      "piata abator",
      "paris",
      "rasaritului",
      "halta marasti",
      "bobalnei est",
      "terapia est",
      "zorilor",
      "spitalul recuperare sud",
      "observatorului sud",
      "gheorghe doja",
      "panselutelor 9",
      "narciselor 19",
      "voronet 85",
      "voronet 24",
      "terapia vest",
      "bobalnei vest",
      "campul painii",
      "piata 1 mai sosire",
      "barbu patriciu",
      "anton pann",
      "i. p. voitesti",
      "teatru",
      "silviu dragomir",
      "observatorului nord",
      "spitalul recuperare nord",
      "gheorghe dima",
      "disp. zorilor",
      "cluj innovation park",
      "vama chinteni",
      "disp. bucium",
      "baza unirea",
      "parang",
      "calvaria",
      "plopilor sud",
      "uzinei electrice",
      "cluj arena",
      "parcul central",
      "george baritiu",
      "facultatea de litere",
      "piata garii vechi",
      "libertatea est",
      "primaria iris",
      "oasului sud",
      "terapia sud",
      "sinterom sud",
      "termorom sud",
      "ers cug sud",
      "unimet sud",
      "amberger sud",
      "depou tramvaie",
      "amberger nord",
      "unimet nord",
      "ers cug nord",
      "termorom nord",
      "sinterom nord",
      "terapia nord",
      "oasului nord",
      "iris nord",
      "piata karl liebknecht",
      "libertatea vest",
      "piata garii noi",
      "horea",
      "opera maghiara est",
      "splaiul independentei",
      "sala sporturilor",
      "plopilor nord",
      "grigore alexandrescu",
      "ravasului",
      "clabucet",
      "aeroport terminal",
      "expo transilvania",
      "aurel vlaicu",
      "arte plastice",
      "crinului",
      "somes",
      "constanta",
      "sora",
      "central",
      "piata mihai viteazul sud",
      "piata mihai viteazul vest",
      "regionala cfr",
      "biserica sf. petru",
      "piata marasti",
      "maresal c-tin. prezan",
      "siretului",
      "pod someseni",
      "libertatea est tram",
      "iris sud tram",
      "oasului sud tram",
      "terapia sud tram",
      "sinterom sud tram",
      "termorom sud tram",
      "ers cug nord tram",
      "termorom nord tram",
      "sinterom nord tram",
      "terapia nord tram",
      "oasului nord tram",
      "iris nord tram",
      "libertatea vest tram",
];

db.createCollection("stations");

db.stations.insertMany(stationNames.map(name => ({ name })));
console.log(`Inserted ${stationNames.length} stations.`);

const allStations = db.stations.find().toArray();
const stationMap = {};

allStations.forEach(s => {
  stationMap[s.name] = s._id;
});

function toIds(names)
{
  return names.map(name => {
    const id = stationMap[name];
    if (!id) {
      console.log(`  ⚠️ Station not found: "${name}"`); // catches typos immediately
    }
    return id;
  });
}

// Create lines collection with all stations
db.createCollection("lines");

const linesToInsert = [
  {
    "number": "102l",
    "direction": "tur",
    "stations": toIds([
      "disp. bucium",
      "baza unirea",
      "parang",
      "calvaria",
      "plopilor sud",
      "uzinei electrice",
      "cluj arena",
      "parcul central",
      "george baritiu",
      "facultatea de litere",
      "piata garii vechi",
      "libertatea est",
      "primaria iris",
      "oasului sud",
      "terapia sud",
      "sinterom sud",
      "termorom sud",
      "ers cug sud",
      "unimet sud",
      "amberger sud",
      "depou tramvaie"
    ])
  },
  {
    "number": "102l",
    "direction": "retur",
    "stations": toIds([
      "depou tramvaie",
      "amberger nord",
      "unimet nord",
      "ers cug nord",
      "termorom nord",
      "sinterom nord",
      "terapia nord",
      "oasului nord",
      "iris nord",
      "piata karl liebknecht",
      "libertatea vest",
      "piata garii noi",
      "horea",
      "opera maghiara est",
      "splaiul independentei",
      "sala sporturilor",
      "plopilor nord",
      "grigore alexandrescu",
      "ravasului",
      "clabucet",
      "disp. bucium"
    ])
  },
  {
    "number": "a1",
    "direction": "tur",
    "stations": toIds([
      "aeroport terminal",
      "expo transilvania",
      "aurel vlaicu",
      "arte plastice",
      "crinului",
      "somes",
      "constanta",
      "sora",
      "central",
      "piata mihai viteazul sud",
      "piata mihai viteazul vest"
    ])
  },
  {
    "number": "a1",
    "direction": "retur",
    "stations": toIds([
      "piata mihai viteazul vest",
      "regionala cfr",
      "biserica sf. petru",
      "piata marasti",
      "maresal c-tin. prezan",
      "siretului",
      "pod someseni",
      "aeroport terminal"
    ])
  },
  {
    "number": "102",
    "direction": "tur",
    "stations": toIds([
      "disp. bucium",
      "baza unirea",
      "parang",
      "calvaria",
      "plopilor sud",
      "uzinei electrice",
      "cluj arena",
      "parcul central",
      "george baritiu",
      "facultatea de litere",
      "piata garii vechi",
      "libertatea est tram",
      "primaria iris",
      "iris sud tram",
      "oasului sud tram",
      "terapia sud tram",
      "sinterom sud tram",
      "termorom sud tram",
      "ers cug sud",
      "unimet sud"
    ])
  },
  {
    "number": "102",
    "direction": "retur",
    "stations": toIds([
      "unimet nord",
      "ers cug nord tram",
      "termorom nord tram",
      "sinterom nord tram",
      "terapia nord tram",
      "oasului nord tram",
      "iris nord tram",
      "piata karl liebknecht",
      "libertatea vest tram",
      "piata garii noi",
      "horea",
      "opera maghiara est",
      "splaiul independentei",
      "sala sporturilor",
      "plopilor nord",
      "grigore alexandrescu",
      "ravasului",
      "clabucet",
      "disp. bucium"
    ])
  },
  {
    "number": "101",
    "direction": "tur",
    "stations": toIds([
      "disp. bucium",
      "baza unirea",
      "parang",
      "calvaria",
      "plopilor sud",
      "uzinei electrice",
      "cluj arena",
      "parcul central",
      "george baritiu",
      "facultatea de litere",
      "piata garii nord"
    ])
  },
  {
    "number": "101",
    "direction": "retur",
    "stations": toIds([
      "piata garii noi",
      "horea",
      "opera maghiara est",
      "splaiul independentei",
      "sala sporturilor",
      "plopilor nord",
      "grigore alexandrescu",
      "ravasului",
      "clabucet"
    ])
  },
  {
    "number": "101a",
    "direction": "tur",
    "stations": toIds([
      "disp. bucium",
      "baza unirea",
      "parang",
      "calvaria",
      "plopilor sud",
      "uzinei electrice",
      "sigismund toduta",
      "hotel napoca",
      "dragalina sud",
      "facultatea de litere",
      "piata garii noi"
    ])
  },
  {
    "number": "101a",
    "direction": "retur",
    "stations": toIds([
      "piata garii noi",
      "horea",
      "dragalina nord",
      "octavian goga",
      "piata 14 iulie nord",
      "plopilor nord",
      "grigore alexandrescu",
      "ravasului",
      "clabucet",
      "disp. bucium"
    ])
  },
  {
    "number": "100l",
    "direction": "tur",
    "stations": toIds([
      "piata garii noi",
      "libertatea est",
      "primaria iris",
      "oasului sud",
      "terapia sud",
      "sinterom sud",
      "termorom sud",
      "ers cug sud",
      "unimet sud",
      "amberger sud",
      "depou tramvaie"
    ])
  },
  {
    "number": "100l",
    "direction": "retur",
    "stations": toIds([
      "depou tramvaie",
      "amberger nord",
      "unimet nord",
      "ers cug nord",
      "termorom nord",
      "sinterom nord",
      "terapia nord",
      "oasului nord",
      "iris nord",
      "piata karl liebknecht",
      "libertatea vest",
      "piata garii noi"
    ])
  },
  {
    "number": "100",
    "direction": "tur",
    "stations": toIds([
      "piata garii vechi",
      "libertatea est tram",
      "primaria iris",
      "iris sud tram",
      "oasului sud tram",
      "terapia sud tram",
      "sinterom sud tram",
      "termorom sud tram",
      "ers cug sud",
      "unimet sud"
    ])
  },
  {
    "number": "100",
    "direction": "retur",
    "stations": toIds([
      "unimet nord",
      "ers cug nord tram",
      "termorom nord tram",
      "sinterom nord tram",
      "terapia nord tram",
      "oasului nord tram",
      "iris nord tram",
      "piata karl liebknecht",
      "libertatea vest tram",
      "piata garii noi"
    ])
  },
  {
    "number": "57l",
    "direction": "tur",
    "stations": toIds([
      "disp. alverna",
      "alverna est",
      "malinului est",
      "c-tin. brancoveanu est",
      "piata cipariu est",
      "septimiu albini sud",
      "nicolae titulescu",
      "herculane",
      "borsec sud",
      "snagov sud",
      "colegiul pedagogic",
      "iulius mall est",
      "campus universitar est",
      "intre lacuri",
      "complex dunarii sud",
      "tulcea",
      "dunarii sud",
      "harghita",
      "jiului sud",
      "aiudului",
      "scoala someseni",
      "depou est",
      "depou tramv sud",
      "emerson"
    ])
  },
  {
    "number": "57l",
    "direction": "retur",
    "stations": toIds([
      "emerson",
      "depou vest",
      "camin someseni",
      "branului",
      "jiului nord",
      "dunarii nord",
      "streiului",
      "complex dunarii nord",
      "campus universitar vest",
      "iulius mall vest",
      "valeriu bologa",
      "snagov nord",
      "borsec nord",
      "bistritei",
      "septimiu albini nord",
      "piata cipariu sud",
      "c-tin. brancoveanu vest",
      "malinului vest",
      "alverna vest",
      "disp. alverna"
    ])
  },
  {
    "number": "57",
    "direction": "tur",
    "stations": toIds([
      "disp. alverna",
      "alverna est",
      "c-tin. brancoveanu est",
      "piata cipariu est",
      "septimiu albini sud",
      "nicolae titulescu",
      "herculane",
      "borsec sud",
      "snagov sud",
      "colegiul pedagogic",
      "iulius mall est",
      "campus universitar est",
      "intre lacuri",
      "complex dunarii sud",
      "tulcea",
      "dunarii sud",
      "harghita",
      "jiului sud",
      "disp. ira"
    ])
  },
  {
    "number": "57",
    "direction": "retur",
    "stations": toIds([
      "disp. ira",
      "jiului",
      "dunarii nord",
      "streiului",
      "complex dunarii nord",
      "campus universitar vest",
      "iulius mall vest",
      "valeriu bologa",
      "snagov nord",
      "borsec nord",
      "bistritei",
      "septimiu albini nord",
      "piata cipariu sud",
      "c-tin. brancoveanu vest",
      "malinului vest",
      "alverna vest",
      "disp. alverna"
    ])
  },
  {
    "number": "56",
    "direction": "tur",
    "stations": toIds([
      "pod traian",
      "closca",
      "piata garii noi",
      "giordano bruno",
      "giordano bruno est",
      "partizanilor est",
      "partizanilor",
      "partizanilor vest",
      "lombului",
      "gheorghe sion vest"
    ])
  },
  {
    "number": "56",
    "direction": "retur",
    "stations": toIds([
      "gheorghe sion vest",
      "gheorghe sion est",
      "spicului nord",
      "spicului sud",
      "giordano bruno est",
      "autogara",
      "piata garii sud",
      "traian",
      "pod traian"
    ])
  },
  {
    "number": "53",
    "direction": "tur",
    "stations": toIds([
      "piata agroalimentara ira",
      "expo transilvania nord",
      "campus utcn nord",
      "arte plastice",
      "bucuresti",
      "farmec",
      "anton pann",
      "piata mihai viteazul vest"
    ])
  },
  {
    "number": "53",
    "direction": "retur",
    "stations": toIds([
      "piata mihai viteazul vest",
      "piata abator",
      "parcul farmec",
      "fabricii",
      "maresal c-tin. prezan",
      "campus utcn sud",
      "expo transilvania sud",
      "piata agroalimentara ira"
    ])
  },
  {
    "number": "52l",
    "direction": "tur",
    "stations": toIds([
      "disp. bucium",
      "bucium",
      "ciobanului",
      "piata flora",
      "calea manastur",
      "agronomia",
      "calea motilor",
      "memorandumului sud",
      "victoria",
      "regionala cfr",
      "ploiesti",
      "paris",
      "rasaritului",
      "halta marasti",
      "bobalnei est",
      "teilor",
      "campina sud",
      "plevnei sud",
      "cet",
      "timisului",
      "branului sud",
      "infratirii sud",
      "dunarii sud",
      "pintea viteazul sud",
      "barc i",
      "depou tram est",
      "emerson"
    ])
  },
  {
    "number": "52l",
    "direction": "retur",
    "stations": toIds([
      "emerson",
      "depou tram nord",
      "i. ionescu",
      "frumoasa",
      "morii",
      "infratirii nord",
      "rodnei",
      "blajului",
      "broda",
      "plevnei nord",
      "campia nord",
      "piata oser",
      "bobalnei vest",
      "campul painii",
      "piata 1 mai",
      "barbu patriciu",
      "anton pann",
      "pod traian",
      "memorandumului nord",
      "spitalul de copii",
      "fabrica de bere",
      "gradini manastur",
      "taberei",
      "calea floresti",
      "academia de muzica",
      "disp. bucium"
    ])
  },
  {
    "number": "52",
    "direction": "tur",
    "stations": toIds([
      "blajului",
      "broda",
      "plevnei nord",
      "campina nord",
      "piata oser",
      "bobalnei vest",
      "piata 1 mai",
      "barbu patriciu",
      "anton pann",
      "pod traian",
      "memorandumului nord",
      "spitalul de copii",
      "fabrica de bere",
      "gradini manastur",
      "taberei",
      "calea floresti",
      "academia de muzica",
      "disp. bucium"
    ])
  },
  {
    "number": "52",
    "direction": "retur",
    "stations": toIds([
      "disp. bucium",
      "bucium",
      "ciobanului",
      "piata flora",
      "calea manastur",
      "agronomia",
      "calea motilor",
      "memorandumului sud",
      "victoria",
      "regionala cfr",
      "ploiesti",
      "paris",
      "rasaritului",
      "piata marasti",
      "bobalnei est",
      "teilor",
      "campina sud",
      "plevnei sud",
      "cet",
      "timisului"
    ])
  },
  {
    "number": "50l",
    "direction": "tur",
    "stations": toIds([
      "disp. zorilor",
      "zorilor",
      "spitalul de recuperare sud",
      "observatorului sud",
      "gheorghe doja",
      "piata cipariu nord",
      "piata avram iancu",
      "piata mihai viteazul est",
      "piata abator",
      "paris",
      "rasaritului",
      "halta marasti",
      "bobalnei est",
      "terapia est",
      "terapia sud",
      "sinterom sud",
      "sieta",
      "termorom sud",
      "ers cug sud",
      "unimet sud",
      "amberger sud",
      "depou tram sud",
      "emerson"
    ])
  },
  {
    "number": "50l",
    "direction": "retur",
    "stations": toIds([
      "emerson",
      "depou tram nord",
      "amberger nord",
      "unimet nord",
      "ers cug nord",
      "termorom nord",
      "sinterom nord",
      "terapia nord",
      "terapia vest",
      "bobalnei vest",
      "campul painii",
      "piata 1 mai",
      "barbu patriciu",
      "anton pann",
      "i. p. voitesti nord",
      "opera",
      "silviu dragomir",
      "observatorului nord",
      "spitalul de recuperare nord",
      "gheorghe dima"
    ])
  },
  {
    "number": "50",
    "direction": "tur",
    "stations": toIds([
      "disp. zorilor",
      "zorilor",
      "spitalul de recuperare sud",
      "observatorului sud",
      "gheorghe doja",
      "piata cipariu nord",
      "piata avram iancu",
      "piata mihai viteazul est",
      "piata abator",
      "paris",
      "rasaritului",
      "halta marasti",
      "bobalnei est",
      "terapia est",
      "terapia sud",
      "sinterom sud",
      "sieta",
      "termorom sud",
      "ers cug sud"
    ])
  },
  {
    "number": "50",
    "direction": "retur",
    "stations": toIds([
      "disp. ers cug",
      "ers cug nord",
      "termorom nord",
      "sinterom nord",
      "terapia nord",
      "terapia vest",
      "bobalnei vest",
      "campul painii",
      "piata 1 mai",
      "barbu patriciu",
      "anton pann",
      "i. p. voitesti nord",
      "opera",
      "silviu dragomir",
      "observatorului nord",
      "spitalul de recuperare nord",
      "gheorghe dima"
    ])
  },
  {
    "number": "48l",
    "direction": "tur",
    "stations": toIds([
      "baisoara",
      "baita",
      "herculane",
      "borsec sud",
      "snagov sud",
      "colegiul pedagogic",
      "iulius mall est",
      "campus universitar est",
      "arte plastice",
      "maresal al. averescu",
      "bobalnei est",
      "terapia est",
      "terapia sud",
      "sinterom sud",
      "sieta",
      "termorom sud",
      "ers cug sud",
      "unimet sud",
      "amberger sud",
      "depou tram sud",
      "emerson"
    ])
  },
  {
    "number": "48l",
    "direction": "retur",
    "stations": toIds([
      "emerson",
      "depou tram nord",
      "amberger nord",
      "unimet nord",
      "ers cug nord",
      "termorom nord",
      "sinterom nord",
      "terapia nord",
      "terapia vest",
      "bobalnei vest",
      "fabricii",
      "maresal c-tin. prezan",
      "dorobantilor",
      "campus universitar vest",
      "iulius mall vest",
      "valeriu bologa",
      "snagov nord",
      "borsec nord",
      "albac",
      "baisoara"
    ])
  },
  {
    "number": "48",
    "direction": "tur",
    "stations": toIds([
      "baisoara",
      "baita",
      "herculane",
      "borsec sud",
      "snagov sud",
      "colegiul pedagogic",
      "iulius mall est",
      "campus universitar est",
      "arte plastice",
      "maresal al. averescu",
      "bobalnei est",
      "terapia est",
      "terapia sud",
      "sinterom sud",
      "sieta",
      "termorom sud",
      "ers cug sud"
    ])
  },
  {
    "number": "48",
    "direction": "retur",
    "stations": toIds([
      "disp. ers cug",
      "ers cug nord",
      "termorom nord",
      "sinterom nord",
      "terapia nord",
      "terapia vest",
      "bobalnei vest",
      "fabricii",
      "maresal c-tin. prezan",
      "dorobantilor",
      "campus universitar vest",
      "iulius mall vest",
      "valeriu bologa",
      "snagov nord",
      "borsec nord",
      "albac",
      "baisoara"
    ])
  },
  {
    "number": "47",
    "direction": "tur",
    "stations": toIds([
      "disp. ira",
      "jiului",
      "dunarii nord",
      "streiului",
      "complex dunarii nord",
      "statia muresului",
      "arte plastice",
      "crinului",
      "somes",
      "constanta",
      "sora",
      "central",
      "piata mihai viteazul sud"
    ])
  },
  {
    "number": "47",
    "direction": "retur",
    "stations": toIds([
      "piata mihai viteazul sud",
      "regionala cfr",
      "biserica sf. petru",
      "piata marasti",
      "maresal c-tin. prezan",
      "intre lacuri",
      "complex dunarii sud",
      "tulcea",
      "dunarii sud",
      "harghita",
      "jiului",
      "disp. ira"
    ])
  },
  {
    "number": "46l",
    "direction": "tur",
    "stations": toIds([
      "vila tusa",
      "d. d. rosca est",
      "dianei est",
      "hotel stil est",
      "e. ionesco",
      "n. steinhardt",
      "v. stoica",
      "zorilor",
      "spitalul de recuperare sud",
      "observatorului sud",
      "gheorghe doja",
      "piata cipariu nord",
      "piata avram iancu",
      "opera"
    ])
  },
  {
    "number": "46l",
    "direction": "retur",
    "stations": toIds([
      "opera",
      "silviu dragomir",
      "observatorului nord",
      "spitalul de recuperare nord",
      "gheorghe dima",
      "picasso",
      "l. matis",
      "luminii",
      "hotel stil vest",
      "dianei vest",
      "d. d. rosca vest",
      "vila tusa"
    ])
  },
  {
    "number": "46b",
    "direction": "tur",
    "stations": toIds([
      "disp. ira",
      "expo transilvania",
      "aurel vlaicu",
      "arte plastice",
      "crinului",
      "somes",
      "constanta",
      "opera",
      "silviu dragomir",
      "observatorului nord",
      "spitalul de recuperare nord",
      "gheorghe dima"
    ])
  },
  {
    "number": "46b",
    "direction": "retur",
    "stations": toIds([
      "disp. zorilor",
      "zorilor",
      "spitalul de recuperare sud",
      "observatorului sud",
      "gheorghe doja",
      "piata cipariu nord",
      "tribunal",
      "scoala s. barnutiu",
      "biblioteca judeteana",
      "maresal c-tin. prezan",
      "siretului",
      "pod someseni"
    ])
  },
  {
    "number": "46",
    "direction": "tur",
    "stations": toIds([
      "giratie drum faget",
      "e. ionesco",
      "n. steinhardt",
      "v. stoica",
      "zorilor",
      "spitalul de recuperare sud",
      "observatorului sud",
      "gheorghe doja",
      "piata cipariu nord",
      "piata avram iancu",
      "teatru"
    ])
  },
  {
    "number": "46",
    "direction": "retur",
    "stations": toIds([
      "opera",
      "silviu dragomir",
      "observatorului nord",
      "spitalul de recuperare nord",
      "gheorghe dima",
      "picasso",
      "l. matis",
      "luminii"
    ])
  },
  {
    "number": "45",
    "direction": "tur",
    "stations": toIds([
      "disp. zorilor",
      "zorilor",
      "spitalul de recuperare sud",
      "observatorului sud",
      "meteor",
      "c-tin. noica",
      "compl. tempus sud",
      "vitacom sud",
      "trifoiului sud",
      "pinului",
      "alverna est",
      "malinului est",
      "c-tin. brancoveanu est",
      "piata cipariu nord",
      "tribunal",
      "rubin patitia",
      "simion barnutiu",
      "biblioteca judeteana",
      "campus universitar vest",
      "iulius mall vest",
      "valeriu bologa",
      "disp. unirii"
    ])
  },
  {
    "number": "45",
    "direction": "retur",
    "stations": toIds([
      "disp. unirii",
      "colegiul pedagogic",
      "iulius mall est",
      "slanic",
      "bistritei",
      "septimiu albini nord",
      "piata cipariu sud",
      "c-tin. brancoveanu vest",
      "malinului vest",
      "alverna vest",
      "artarului",
      "fagului",
      "trifoiului nord",
      "vitacom nord",
      "compl. tempus nord",
      "electrogroup",
      "w. a. mozart",
      "observatorului nord",
      "spitalul de recuperare nord",
      "gheorghe dima",
      "disp. zorilor"
    ])
  },
  {
    "number": "44",
    "direction": "tur",
    "stations": toIds([
      "disp. grigorescu",
      "radio romania cluj",
      "petuniei",
      "iancu de hunedoara",
      "piata 14 iulie sud",
      "hotel napoca",
      "parcul central",
      "piata mihai viteazul sud",
      "tribunal",
      "rubin patitia",
      "simion barnutiu",
      "biblioteca judeteana",
      "campus universitar est",
      "iulius mall vest",
      "valeriu bologa",
      "soporului sud",
      "soporului"
    ])
  },
  {
    "number": "44",
    "direction": "retur",
    "stations": toIds([
      "soporului",
      "soporului nord",
      "colegiul pedagogic",
      "iulius mall est",
      "slanic",
      "bistritei",
      "septimiu albini nord",
      "piata cipariu nord",
      "piata avram iancu",
      "sora",
      "central",
      "dragalina nord",
      "octavian goga",
      "piata 14 iulie nord",
      "alexandru vlahuta",
      "buzau",
      "miraslau",
      "fantanele",
      "disp. grigorescu"
    ])
  },
  {
    "number": "43p",
    "direction": "tur",
    "stations": toIds([
      "observatorului nord",
      "spitalul de recuperare nord",
      "gheorghe dima",
      "varianta manastur",
      "frunzisului",
      "cocosul de aur",
      "peana",
      "garbau",
      "bucium",
      "nodul nord",
      "vivo! cluj-napoca"
    ])
  },
  {
    "number": "43p",
    "direction": "retur",
    "stations": toIds([
      "vivo! cluj-napoca",
      "polus center",
      "academia de muzica",
      "primaverii",
      "minerva",
      "izlazului",
      "frunzisului vest",
      "varianta zorilor sud",
      "zorilor",
      "spitalul de recuperare sud",
      "observatorului sud"
    ])
  },
  {
    "number": "43b",
    "direction": "tur",
    "stations": toIds([
      "disp. grigorescu",
      "radio romania cluj",
      "cora nord",
      "colina",
      "primaverii",
      "minerva",
      "izlazului",
      "frunzisului vest",
      "varianta zorilor sud",
      "zorilor",
      "spitalul de recuperare sud",
      "observatorului sud",
      "meteor",
      "c-tin. noica",
      "hexagon",
      "drum faget",
      "dacia service"
    ])
  },
  {
    "number": "43b",
    "direction": "retur",
    "stations": toIds([
      "dacia service",
      "compexit",
      "electrogroup",
      "w. a. mozart",
      "observatorului nord",
      "spitalul de recuperare nord",
      "gheorghe dima",
      "frunzisului",
      "cocosul de aur",
      "peana",
      "garbau",
      "bucium",
      "cora sud",
      "b-dul 1 decembrie 1918"
    ])
  },
  {
    "number": "43",
    "direction": "tur",
    "stations": toIds([
      "disp. grigorescu",
      "radio romania cluj",
      "cora nord",
      "academia de muzica",
      "primaverii",
      "minerva",
      "izlazului",
      "frunzisului vest",
      "varianta zorilor sud",
      "zorilor",
      "spitalul de recuperare sud",
      "observatorului sud",
      "observatorului nord"
    ])
  },
  {
    "number": "43",
    "direction": "retur",
    "stations": toIds([
      "observatorului nord",
      "spitalul de recuperare nord",
      "gheorghe dima",
      "varianta manastur",
      "frunzisului",
      "cocosul de aur",
      "peana",
      "garbau",
      "bucium",
      "cora sud",
      "b-dul 1 decembrie 1918",
      "disp. grigorescu"
    ])
  },
  {
    "number": "42",
    "direction": "tur",
    "stations": toIds([
      "pod traian",
      "memorandumului nord",
      "spitalul de copii",
      "fabrica de bere",
      "gradini manastur",
      "balea vest",
      "eugen lovinescu vest",
      "grigore antipa vest"
    ])
  },
  {
    "number": "42",
    "direction": "retur",
    "stations": toIds([
      "biserica campului",
      "grigore antipa est",
      "eugen lovinescu est",
      "balea est",
      "calea manastur",
      "agronomia",
      "calea motilor",
      "memorandumului sud",
      "central",
      "piata mihai viteazul sud",
      "pmv flip"
    ])
  },
  {
    "number": "41",
    "direction": "tur",
    "stations": toIds([
      "disp. grigorescu",
      "radio romania cluj",
      "petuniei",
      "iancu de hunedoara",
      "giuseppe garibaldi 4-6",
      "cluj arena",
      "parcul central",
      "piata mihai viteazul sud",
      "p-ta abator",
      "paris",
      "piata 1 mai"
    ])
  },
  {
    "number": "41",
    "direction": "retur",
    "stations": toIds([
      "piata 1 mai",
      "barbu patriciu",
      "anton pann",
      "dacia",
      "dragalina nord",
      "octavian goga",
      "george enescu",
      "alexandru vlahuta",
      "buzau",
      "miraslau",
      "fantanele",
      "disp. grigorescu"
    ])
  },
  {
    "number": "40",
    "direction": "tur",
    "stations": toIds([
      "opera",
      "silviu dragomir",
      "meteor",
      "c-tin. noica",
      "centrul medical",
      "drum faget",
      "hotel stil vest",
      "dianei vest",
      "d. d. rosca vest",
      "vila tusa"
    ])
  },
  {
    "number": "40",
    "direction": "retur",
    "stations": toIds([
      "vila tusa",
      "d. d. rosca est",
      "dianei est",
      "hotel stil est",
      "dacia service",
      "compexit",
      "electrogroup",
      "w. a. mozart",
      "calea turzii",
      "gheorghe doja",
      "piata cipariu nord",
      "piata avram iancu",
      "teatru"
    ])
  },
  {
    "number": "39l",
    "direction": "tur",
    "stations": toIds([
      "piata mihai viteazul est",
      "closca",
      "piata garii noi",
      "giordano bruno",
      "senina sud",
      "dragos voda sud",
      "vrancea",
      "calugareni sud",
      "iris sud",
      "vama chinteni",
      "intermediara est",
      "pometului est",
      "scoala est",
      "ias est",
      "pod est",
      "drum feiurd est",
      "creic",
      "podul fetei est",
      "bis. greco catolica est",
      "terra est",
      "cluj due est",
      "catun vest"
    ])
  },
  {
    "number": "39l",
    "direction": "retur",
    "stations": toIds([
      "catun vest",
      "cluj due vest",
      "terra vest",
      "bis. greco catolica vest",
      "podul fetei vest",
      "creic",
      "drum feiurd vest",
      "pod vest",
      "ias vest",
      "scoala vest",
      "pometului vest",
      "intermediara vest",
      "oasului nord",
      "iris nord",
      "calugareni nord",
      "spataru milescu",
      "dragos voda nord",
      "senina nord",
      "autogara",
      "piata garii vest",
      "scoala horea",
      "piata mihai viteazul est"
    ])
  },
  {
    "number": "39",
    "direction": "tur",
    "stations": toIds([
      "piata mihai viteazul est",
      "closca",
      "piata garii noi",
      "giordano bruno",
      "senina sud",
      "dragos voda sud",
      "vrancea",
      "calugareni sud",
      "iris sud",
      "vama chinteni",
      "intermediara est",
      "pometului est",
      "scoala est",
      "ias est",
      "pod est",
      "drum feiurd est",
      "podul fetei est",
      "bis. greco catolica est",
      "valea chintaului"
    ])
  },
  {
    "number": "39",
    "direction": "retur",
    "stations": toIds([
      "valea chintaului",
      "bis. greco catolica vest",
      "podul fetei vest",
      "drum feiurd vest",
      "pod vest",
      "ias vest",
      "scoala vest",
      "pometului vest",
      "intermediara vest",
      "oasului nord",
      "iris nord",
      "calugareni nord",
      "spataru milescu",
      "dragos voda nord",
      "senina nord",
      "autogara",
      "piata garii vechi",
      "scoala horea",
      "piata mihai viteazul"
    ])
  },
  {
    "number": "38",
    "direction": "tur",
    "stations": toIds([
      "piata mihai viteazul est",
      "emil racovita nord",
      "trambitasului",
      "vanatorului"
    ])
  },
  {
    "number": "38",
    "direction": "retur",
    "stations": toIds([
      "vanatorului",
      "gruia",
      "baia mare",
      "crisan",
      "scoala horea",
      "piata mihai viteazul sud",
      "piata mihai viteazul est"
    ])
  },
  {
    "number": "37",
    "direction": "tur",
    "stations": toIds([
      "piata mihai viteazul est",
      "emil racovita nord",
      "arena cfr nord",
      "radauti nord",
      "tiberiu brediceanu",
      "bariera cfr nord",
      "tetarom",
      "energobit nord",
      "tetarom vest"
    ])
  },
  {
    "number": "37",
    "direction": "retur",
    "stations": toIds([
      "tetarom vest",
      "energobit sud",
      "bariera cfr sud",
      "vasile carlova",
      "radauti sud",
      "stadionul cfr",
      "crisan",
      "scoala horea",
      "piata mihai viteazul sud",
      "piata mihai viteazul est"
    ])
  },
  {
    "number": "36l",
    "direction": "tur",
    "stations": toIds([
      "piata mihai viteazul vest",
      "piata abator",
      "parcul farmec",
      "maresal al. averescu",
      "bobalnei est",
      "campina sud",
      "plevnei sud",
      "cet",
      "timisului sud",
      "branului sud",
      "infratirii sud",
      "pintea viteazul sud",
      "barc i",
      "depou est",
      "depou tram sud",
      "emerson"
    ])
  },
  {
    "number": "36l",
    "direction": "retur",
    "stations": toIds([
      "emerson",
      "depou tram nord",
      "depou vest",
      "i. ionescu",
      "frumoasa",
      "morii",
      "infratirii nord",
      "rodnei",
      "blajului",
      "broda",
      "plevnei nord",
      "campina nord",
      "bobalnei vest",
      "bucuresti",
      "farmec",
      "anton pann",
      "piata mihai viteazul vest"
    ])
  },
  {
    "number": "36b",
    "direction": "tur",
    "stations": toIds([
      "piata mihai viteazul vest",
      "piata abator",
      "parcul farmec",
      "maresal al. averescu",
      "bobalnei est",
      "teilor",
      "campina sud",
      "plevnei sud",
      "cet",
      "timisului",
      "branului sud",
      "infratirii sud",
      "pintea viteazul sud",
      "barc i",
      "i. ionescu"
    ])
  },
  {
    "number": "36b",
    "direction": "retur",
    "stations": toIds([
      "i. ionescu",
      "frumoasa",
      "morii",
      "infratirii nord",
      "rodnei",
      "blajului",
      "broda",
      "plevnei nord",
      "campina nord",
      "piata oser",
      "bobalnei vest",
      "bucuresti",
      "farmec",
      "anton pann",
      "piata mihai viteazul"
    ])
  },
  {
    "number": "35",
    "direction": "tur",
    "stations": toIds([
      "disp. zorilor",
      "zorilor",
      "spitalul de recuperare sud",
      "observatorului sud",
      "gheorghe doja",
      "piata cipariu nord",
      "piata avram iancu",
      "sora",
      "central",
      "closca",
      "piata garii sud"
    ])
  },
  {
    "number": "35",
    "direction": "retur",
    "stations": toIds([
      "piata garii sud",
      "traian",
      "i. p. voitesti",
      "opera",
      "silviu dragomir",
      "observatorului nord",
      "spitalul de recuperare nord",
      "gheorghe dima"
    ])
  },
  {
    "number": "34",
    "direction": "tur",
    "stations": toIds([
      "piata garii sud",
      "blanarilor",
      "rasaritului",
      "halta marasti",
      "fabricii",
      "maresal c-tin. prezan",
      "dorobantilor",
      "campus universitar vest",
      "iulius mall vest",
      "valeriu bologa",
      "snagov nord",
      "borsec nord",
      "albac",
      "baisoara"
    ])
  },
  {
    "number": "34",
    "direction": "retur",
    "stations": toIds([
      "baisoara",
      "baita",
      "herculane",
      "borsec sud",
      "snagov sud",
      "colegiul pedagogic",
      "iulius mall est",
      "campus universitar est",
      "arte plastice",
      "maresal al. averescu",
      "campul painii",
      "piata 1 mai",
      "parcul feroviarilor",
      "piata garii nord"
    ])
  },
  {
    "number": "33",
    "direction": "tur",
    "stations": toIds([
      "baisoara",
      "baita",
      "bistritei",
      "septimiu albini nord",
      "piata cipariu nord",
      "piata avram iancu",
      "pmv 2"
    ])
  },
  {
    "number": "33",
    "direction": "retur",
    "stations": toIds([
      "piata mihai viteazul vest",
      "teatru",
      "piata cipariu est",
      "septimiu albini sud",
      "nicolae titulescu",
      "albac",
      "baisoara"
    ])
  },
  {
    "number": "32b",
    "direction": "tur",
    "stations": toIds([
      "disp. alverna",
      "alverna est",
      "malinului est",
      "c-tin. brancoveanu est",
      "piata cipariu nord",
      "piata avram iancu",
      "sora",
      "central",
      "closca",
      "piata garii"
    ])
  },
  {
    "number": "32b",
    "direction": "retur",
    "stations": toIds([
      "piata garii sud",
      "traian",
      "piata mihai viteazul vest",
      "teatru",
      "piata cipariu sud",
      "c-tin. brancoveanu vest",
      "malinului vest",
      "alverna vest"
    ])
  },
  {
    "number": "32",
    "direction": "tur",
    "stations": toIds([
      "disp. alverna",
      "alverna est",
      "malinului est",
      "c-tin. brancoveanu est",
      "piata cipariu nord",
      "piata avram iancu",
      "pmv 2"
    ])
  },
  {
    "number": "32",
    "direction": "retur",
    "stations": toIds([
      "piata mihai viteazul vest",
      "teatru",
      "piata cipariu sud",
      "c-tin. brancoveanu vest",
      "malinului vest",
      "alverna vest"
    ])
  },
  {
    "number": "31",
    "direction": "tur",
    "stations": toIds([
      "piata mihai viteazul est",
      "closca",
      "piata garii nord",
      "giordano bruno",
      "fagaras",
      "livezeni",
      "t. vladimirescu nord",
      "valea seaca",
      "cartier baciu",
      "fabrica de paine nord",
      "napolact"
    ])
  },
  {
    "number": "31",
    "direction": "retur",
    "stations": toIds([
      "napolact",
      "fabrica de paine sud",
      "calea baciului",
      "t. vladimirescu sud",
      "soarelui",
      "trandafirilor",
      "autogara",
      "piata garii vechi",
      "scoala horea",
      "pmv 1"
    ])
  },
  {
    "number": "30",
    "direction": "tur",
    "stations": toIds([
      "disp. grigorescu",
      "radio romania cluj",
      "petuniei",
      "iancu de hunedoara",
      "giuseppe garibaldi",
      "cluj arena",
      "hotel radinsson blu",
      "calea motilor",
      "memorandumului sud",
      "victoria",
      "regionala cfr",
      "biserica sf. petru",
      "piata marasti",
      "maresal c-tin. prezan",
      "siretului",
      "pod someseni",
      "disp. ira"
    ])
  },
  {
    "number": "30",
    "direction": "retur",
    "stations": toIds([
      "disp. ira",
      "expo transilvania",
      "aurel vlaicu",
      "arte plastice",
      "crinului",
      "somes",
      "constanta",
      "sora",
      "memorandumului nord",
      "spitalul de copii",
      "chios",
      "splaiul independentei",
      "george enescu",
      "alexandru vlahuta",
      "buzau",
      "miraslau",
      "fantanele",
      "disp. grigorescu"
    ])
  },
  {
    "number": "29s",
    "direction": "tur",
    "stations": toIds([
      "roata faget",
      "bucium",
      "ciobanului",
      "piata flora",
      "calea manastur",
      "agronomia",
      "calea motilor",
      "memorandumului sud",
      "central",
      "piata mihai viteazul sud"
    ])
  },
  {
    "number": "29s",
    "direction": "retur",
    "stations": toIds([
      "pod traian",
      "memorandumului nord",
      "spitalul de copii",
      "fabrica de bere",
      "gradini manastur",
      "taberei",
      "calea floresti",
      "academia de muzica",
      "roata faget"
    ])
  },
  {
    "number": "29",
    "direction": "tur",
    "stations": toIds([
      "roata faget pl",
      "budum",
      "ciobanului",
      "piata flora",
      "calea manastur",
      "agronomia",
      "calea motilor",
      "memorandumului sud",
      "central",
      "piata mihai viteazul sud",
      "p-ta abator",
      "henri barbusse"
    ])
  },
  {
    "number": "29",
    "direction": "retur",
    "stations": toIds([
      "henri barbusse pl.",
      "bucuresti",
      "farmec",
      "anton pann",
      "pod traian",
      "memorandumului nord",
      "spitalul de copii",
      "fabrica de bere",
      "gradini manastur",
      "taberei",
      "calea floresti",
      "academia de muzica",
      "roata faget"
    ])
  },
  {
    "number": "28b",
    "direction": "tur",
    "stations": toIds([
      "vivo! cluj-napoca",
      "polus center",
      "cora sud",
      "b-dul 1 decembrie 1918",
      "petuniei",
      "iancu de hunedoara",
      "piata 14 iulie sud",
      "hotel napoca",
      "parcul central",
      "piata mihai viteazul sud"
    ])
  },
  {
    "number": "28b",
    "direction": "retur",
    "stations": toIds([
      "piata mihai viteazul sud",
      "dacia",
      "dragalina nord",
      "octavian goga",
      "piata 14 iulie nord",
      "alexandru vlahuta",
      "buzau",
      "miraslau",
      "cora nord",
      "nodul nord",
      "vivo! cluj-napoca"
    ])
  },
  {
    "number": "28",
    "direction": "tur",
    "stations": toIds([
      "disp. grigorescu",
      "radio romania cluj",
      "petuniei",
      "iancu de hunedoara",
      "piata 14 iulie sud",
      "hotel napoca",
      "parcul central",
      "piata mihai viteazul sud"
    ])
  },
  {
    "number": "28",
    "direction": "retur",
    "stations": toIds([
      "piata mihai viteazul sud",
      "dacia",
      "dragalina nord",
      "octavian goga",
      "piata 14 iulie nord",
      "alexandru vlahuta",
      "buzau",
      "miraslau",
      "fantanele",
      "disp. grigorescu"
    ])
  },
  {
    "number": "27",
    "direction": "tur",
    "stations": toIds([
      "disp. grigorescu",
      "radio romania cluj",
      "petuniei",
      "iancu de hunedoara",
      "giuseppe garibaldi 4-6",
      "cluj arena",
      "dragalina sud",
      "closca",
      "piata garii sud"
    ])
  },
  {
    "number": "27",
    "direction": "retur",
    "stations": toIds([
      "piata garii sud",
      "traian",
      "dacia",
      "dragalina nord",
      "octavian goga",
      "piata 14 iulie nord",
      "alexandru vlahuta",
      "buzau",
      "miraslau",
      "fantanele",
      "disp. grigorescu"
    ])
  },
  {
    "number": "26l",
    "direction": "tur",
    "stations": toIds([
      "radio romania cluj",
      "petuniei",
      "iancu de hunedoara",
      "giuseppe garibaldi 4-6",
      "cluj arena",
      "parcul central",
      "piata mihai viteazul sud",
      "grupul scolar cfr est",
      "libertatea est",
      "gheorghe asachi",
      "iris sud",
      "oasului sud",
      "terapia sud",
      "sinterom sud",
      "sieta",
      "termorom sud",
      "ers cug sud",
      "unimet sud",
      "amberger sud",
      "depou tram sud",
      "emerson"
    ])
  },
  {
    "number": "26l",
    "direction": "retur",
    "stations": toIds([
      "emerson",
      "depou tram nord",
      "amberger nord",
      "unimet nord",
      "ers cug nord tram",
      "termorom nord",
      "sinterom nord",
      "terapia nord",
      "oasului nord",
      "iris nord",
      "puietilor",
      "libertatea vest",
      "traian",
      "dacia",
      "dragalina nord",
      "octavian goga",
      "piata 14 iulie nord",
      "alexandru vlahuta",
      "buzau",
      "miraslau",
      "fantanele",
      "disp. grigorescu"
    ])
  },
  {
    "number": "26",
    "direction": "tur",
    "stations": toIds([
      "disp. grigorescu",
      "radio romania cluj",
      "petuniei",
      "iancu de hunedoara",
      "giuseppe garibaldi 4-6",
      "cluj arena",
      "parcul central",
      "piata mihai viteazul sud",
      "politia est",
      "grupul scolar cfr est",
      "libertatea est",
      "gheorghe asachi",
      "iris sud",
      "oasului sud",
      "terapia sud",
      "sinterom sud",
      "sieta",
      "termorom sud",
      "ers cug sud"
    ])
  },
  {
    "number": "26",
    "direction": "retur",
    "stations": toIds([
      "disp. ers cug",
      "ers cug nord",
      "termorom nord",
      "sinterom nord",
      "terapia nord",
      "oasului nord",
      "iris nord",
      "puietilor",
      "libertatea vest",
      "traian",
      "dacia",
      "dragalina nord",
      "octavian goga",
      "george enescu",
      "alexandru vlahuta",
      "buzau",
      "miraslau",
      "fantanele",
      "disp. grigorescu"
    ])
  },
  {
    "number": "25",
    "direction": "tur",
    "stations": toIds([
      "disp. clabucet",
      "primaverii",
      "minerva",
      "izlazului",
      "calea manastur",
      "agronomia",
      "calea motilor",
      "memorandumului sud",
      "victoria",
      "regionala cfr",
      "biserica sf. petru",
      "piata marasti",
      "maresal c-tin. prezan",
      "dorobantilor",
      "campus universitar vest",
      "iulius mall vest",
      "valeriu bologa"
    ])
  },
  {
    "number": "25",
    "direction": "retur",
    "stations": toIds([
      "snagov nord",
      "borsec nord",
      "bistritei",
      "septimiu albini nord",
      "piata cipariu nord",
      "piata avram iancu",
      "sora",
      "memorandumului nord",
      "spitalul de copii",
      "fabrica de bere",
      "gradini manastur",
      "ion mester",
      "peana",
      "garbau"
    ])
  },
  {
    "number": "24b",
    "direction": "tur",
    "stations": toIds([
      "disp. unirii",
      "colegiul pedagogic",
      "iulius mall est",
      "campus universitar est",
      "arte plastice",
      "crinului",
      "somes",
      "constanta",
      "sora",
      "memorandumului nord",
      "spitalul de copii",
      "fabrica de bere",
      "gradini manastur",
      "taberei",
      "calea floresti",
      "nodul nord",
      "vivo! cluj-napoca"
    ])
  },
  {
    "number": "24b",
    "direction": "retur",
    "stations": toIds([
      "vivo! cluj-napoca",
      "polus center",
      "ciobanului",
      "piata flora",
      "calea manastur",
      "agronomia",
      "calea motilor",
      "memorandumului sud",
      "victoria",
      "regionala cfr",
      "biserica sf. petru",
      "piata marasti",
      "maresal c-tin. prezan",
      "dorobantilor",
      "campus universitar vest",
      "iulius mall vest",
      "valeriu bologa",
      "disp. unirii"
    ])
  },
  {
    "number": "24",
    "direction": "tur",
    "stations": toIds([
      "disp. unirii",
      "colegiul pedagogic",
      "iulius mall est",
      "campus universitar est",
      "arte plastice",
      "crinului",
      "somes",
      "constanta",
      "sora",
      "memorandumului nord",
      "spitalul de copii",
      "fabrica de bere",
      "gradini manastur",
      "taberei",
      "calea floresti",
      "academia de muzica",
      "disp. bucium"
    ])
  },
  {
    "number": "24",
    "direction": "retur",
    "stations": toIds([
      "disp. bucium",
      "bucium",
      "ciobanului",
      "piata flora",
      "calea manastur",
      "agronomia",
      "calea motilor",
      "memorandumului sud",
      "victoria",
      "regionala cfr",
      "biserica sf. petru",
      "piata marasti",
      "maresal c-tin. prezan",
      "dorobantilor",
      "campus universitar vest",
      "iulius mall vest",
      "valeriu bologa",
      "disp. unirii"
    ])
  },
  {
    "number": "23",
    "direction": "tur",
    "stations": toIds([
      "i. p. voitesti nord",
      "regionala cfr",
      "ploiesti",
      "paris",
      "rasaritului",
      "halta marasti",
      "bobalnei est",
      "terapia est",
      "terapia sud",
      "sinterom sud",
      "sieta",
      "termorom sud",
      "ers cug sud"
    ])
  },
  {
    "number": "23",
    "direction": "retur",
    "stations": toIds([
      "disp. ers cug",
      "ers cug nord",
      "termorom nord",
      "sinterom nord",
      "terapia nord",
      "terapia vest",
      "bobalnei vest",
      "campul painii",
      "piata 1 mai",
      "barbu patriciu",
      "anton pann",
      "i. p. voitesti nord"
    ])
  },
  {
    "number": "22",
    "direction": "tur",
    "stations": toIds([
      "piata garii",
      "traian",
      "pod traian",
      "memorandumului nord",
      "ion creanga",
      "hasdeu",
      "c. porumbescu",
      "boli infectioase"
    ])
  },
  {
    "number": "22",
    "direction": "retur",
    "stations": toIds([
      "spitalul boli infectioase",
      "v. babes",
      "memorandumului sud",
      "central",
      "closca",
      "piata garii"
    ])
  },
  {
    "number": "21",
    "direction": "tur",
    "stations": toIds([
      "piata mihai viteazul vest",
      "opera",
      "piata cipariu sud",
      "piata i. agarbiceanu vest",
      "drapelului vest",
      "becas vest",
      "fagului",
      "trifoiului nord",
      "vitacom nord",
      "compl. tempus nord",
      "hexagon",
      "drum faget",
      "dacia service"
    ])
  },
  {
    "number": "21",
    "direction": "retur",
    "stations": toIds([
      "dacia service",
      "compexit",
      "compl. tempus sud",
      "vitacom sud",
      "trifoiului sud",
      "becas est",
      "drapelului est",
      "piata i. agarbiceanu est",
      "andrei muresanu est",
      "piata cipariu nord",
      "piata avram iancu",
      "piata mihai viteazul vest"
    ])
  },
  {
    "number": "20",
    "direction": "tur",
    "stations": toIds([
      "biserica borhanci est",
      "voievodul menumorut est",
      "voievodul glad est",
      "theodor pallady",
      "borhanciului",
      "sere usamv nord",
      "alverna est",
      "malinului est",
      "c-tin. brancoveanu est",
      "posada"
    ])
  },
  {
    "number": "20",
    "direction": "retur",
    "stations": toIds([
      "posada",
      "piata cipariu sud",
      "c-tin. brancoveanu vest",
      "malinului vest",
      "alverna vest",
      "sere usamv sud",
      "antim ivireanul",
      "violetelor",
      "voievodul glad vest",
      "voievodul menumorut vest",
      "biserica borhanci vest"
    ])
  },
  {
    "number": "19",
    "direction": "tur",
    "stations": toIds([
      "pod traian",
      "memorandumului nord",
      "spitalul de copii",
      "fabrica de bere",
      "gradini manastur",
      "balea vest",
      "dimitrie gusti",
      "e. quinet vest",
      "e. quinet sud"
    ])
  },
  {
    "number": "19",
    "direction": "retur",
    "stations": toIds([
      "e. quinet sud",
      "e. quinet nord",
      "scoala edmund nicolau",
      "a.n.l.",
      "gradinita mehedinti",
      "izlazului",
      "calea manastur",
      "agronomia",
      "calea motilor",
      "memorandumului sud",
      "central",
      "piata mihai viteazul sud",
      "pod traian"
    ])
  },
  {
    "number": "18",
    "direction": "tur",
    "stations": toIds([
      "posada",
      "piata cipariu sud",
      "c-tin. brancoveanu vest",
      "malinului vest",
      "alverna vest",
      "antonio gaudi nord",
      "statia nordului vest",
      "uranus vest",
      "romul ladea vest",
      "dimitrie onciul vest",
      "veseliei"
    ])
  },
  {
    "number": "18",
    "direction": "retur",
    "stations": toIds([
      "veseliei",
      "dimitrie onciul est",
      "romul ladea est",
      "uranus est",
      "statia nordului est",
      "antonio gaudi sud",
      "alverna est",
      "malinului est",
      "c-tin. brancoveanu est",
      "posada"
    ])
  },
  {
    "number": "12",
    "direction": "tur",
    "stations": toIds([
      "disp. ira",
      "expo transilvania",
      "aurel vlaicu",
      "arte plastice",
      "maresal al. averescu",
      "bobalnei est",
      "terapia est",
      "terapia sud",
      "sinterom sud",
      "sieta",
      "termorom sud",
      "ers cug sud"
    ])
  },
  {
    "number": "12",
    "direction": "retur",
    "stations": toIds([
      "ers cug sud",
      "ers cug nord",
      "termorom nord",
      "sinterom nord",
      "terapia nord",
      "terapia vest",
      "bobalnei vest",
      "fabricii",
      "maresal c-tin. prezan",
      "siretului",
      "pod someseni",
      "disp. ira"
    ])
  },
  {
    "number": "14",
    "direction": "tur",
    "stations": toIds([
      "ers cug nord",
      "termorom nord",
      "sinterom nord",
      "terapia nord",
      "terapia vest",
      "bobalnei vest",
      "fabricii",
      "crinului",
      "somes",
      "constanta",
      "sora",
      "memorandumului nord",
      "spitalul de copii",
      "fabrica de bere",
      "gradini manastur",
      "ion mester",
      "peana",
      "garbau",
      "disp. clabucet"
    ])
  },
  {
    "number": "14",
    "direction": "retur",
    "stations": toIds([
      "disp. clabucet",
      "primaverii",
      "minerva",
      "izlazului",
      "calea manastur",
      "agronomia",
      "calea motilor",
      "memorandumului sud",
      "victoria",
      "regionala cfr",
      "biserica sf. petru",
      "piata marasti",
      "maresal al. averescu",
      "bobalnei est",
      "terapia est",
      "terapia sud",
      "sinterom sud",
      "sieta",
      "termorom sud",
      "ers cug sud"
    ])
  },
  {
    "number": "10",
    "direction": "tur",
    "stations": toIds([
      "ers cug sud",
      "ers cug nord",
      "sinterom nord",
      "terapia nord",
      "terapia vest",
      "bobalnei vest",
      "fabricii",
      "maresal c-tin. prezan",
      "dorobantilor",
      "campus universitar vest",
      "iulius mall vest",
      "valeriu bologa",
      "snagov nord"
    ])
  },
  {
    "number": "10",
    "direction": "retur",
    "stations": toIds([
      "snagov nord",
      "borsec nord",
      "bistritei",
      "septimiu albini nord",
      "piata cipariu nord",
      "piata avram iancu",
      "ploiesti",
      "paris",
      "rasaritului",
      "halta marasti",
      "bobalnei est",
      "terapia est",
      "terapia sud",
      "sinterom sud",
      "sieta",
      "termorom sud",
      "ers cug sud"
    ])
  },
  {
    "number": "9",
    "direction": "tur",
    "stations": toIds([
      "disp. bucium",
      "bucium",
      "ciobanului",
      "piata flora",
      "calea manastur",
      "agronomia",
      "calea motilor",
      "memorandumului sud",
      "central",
      "closca",
      "piata garii sud"
    ])
  },
  {
    "number": "9",
    "direction": "retur",
    "stations": toIds([
      "piata garii sud",
      "traian",
      "pod traian",
      "memorandumului nord",
      "spitalul de copii",
      "fabrica de bere",
      "gradini manastur",
      "taberei",
      "calea floresti",
      "academia de muzica",
      "disp. bucium"
    ])
  },
  {
    "number": "8l",
    "direction": "tur",
    "stations": toIds([
      "maresal c-tin. prezan",
      "siretului",
      "pod someseni",
      "selgros",
      "u.m. someseni",
      "dealul borzas",
      "platanilor",
      "henri coanda",
      "halta dezmir",
      "piata agro"
    ])
  },
  {
    "number": "8l",
    "direction": "retur",
    "stations": toIds([
      "agro transilvania",
      "halta agro",
      "r.a.d.p",
      "posta romana",
      "gara someseni",
      "mentenantei",
      "bai someseni",
      "expo transilvania",
      "aurel vlaicu",
      "arte plastice",
      "crinului"
    ])
  },
  {
    "number": "8",
    "direction": "tur",
    "stations": toIds([
      "piata mihai viteazul sud",
      "regionala cfr",
      "biserica sf. petru",
      "piata marasti",
      "maresal c-tin. prezan",
      "siretului",
      "pod someseni",
      "aiudului",
      "scoala someseni",
      "orastie",
      "ambient",
      "mos ion roata",
      "traian vuia sud",
      "aeroport sud",
      "cantonului",
      "electromontaj sud"
    ])
  },
  {
    "number": "8",
    "direction": "retur",
    "stations": toIds([
      "electromontaj nord",
      "aviatia utilitara",
      "aeroport nord",
      "traian vuia nord",
      "planoarelor",
      "vlad tepes",
      "camin someseni",
      "branului",
      "expo transilvania",
      "aurel vlaicu",
      "arte plastice",
      "crinului",
      "somes",
      "constanta",
      "sora",
      "central",
      "piata mihai viteazul sud"
    ])
  },
  {
    "number": "7",
    "direction": "tur",
    "stations": toIds([
      "disp. ira",
      "expo transilvania",
      "aurel vlaicu",
      "arte plastice",
      "crinului",
      "somes",
      "constanta",
      "sora",
      "memorandumului nord",
      "spitalul de copii",
      "fabrica de bere",
      "gradini manastur",
      "ion mester",
      "izlazului"
    ])
  },
  {
    "number": "7",
    "direction": "retur",
    "stations": toIds([
      "izlazului",
      "calea manastur",
      "agronomia",
      "calea motilor",
      "memorandumului sud",
      "victoria",
      "regionala cfr",
      "biserica sf. petru",
      "piata marasti",
      "maresal c-tin. prezan",
      "siretului",
      "pod someseni"
    ])
  },
  {
    "number": "6",
    "direction": "tur",
    "stations": toIds([
      "disp. clabucet",
      "primaverii",
      "minerva",
      "izlazului",
      "calea manastur",
      "agronomia",
      "calea motilor",
      "memorandumului sud",
      "victoria",
      "regionala cfr",
      "biserica sf. petru",
      "piata marasti",
      "maresal c-tin. prezan",
      "siretului",
      "pod someseni"
    ])
  },
  {
    "number": "6",
    "direction": "retur",
    "stations": toIds([
      "disp. ira",
      "expo transilvania",
      "aurel vlaicu",
      "arte plastice",
      "crinului",
      "somes",
      "constanta",
      "sora",
      "memorandumului nord",
      "spitalul de copii",
      "fabrica de bere",
      "gradini manastur",
      "ion mester",
      "peana",
      "garbau"
    ])
  },
  {
    "number": "5",
    "direction": "tur",
    "stations": toIds([
      "piata garii sud",
      "traian",
      "i. p. voitesti sud",
      "regionala cfr",
      "biserica sf. petru",
      "piata marasti",
      "maresal c-tin. prezan",
      "siretului",
      "pod someseni",
      "aiudului",
      "scoala someseni",
      "orastie",
      "ambient",
      "mos ion roata",
      "traian vuia sud",
      "aeroport sud",
      "cantonului",
      "electromontaj sud",
      "lukoil traian vuia"
    ])
  },
  {
    "number": "5",
    "direction": "retur",
    "stations": toIds([
      "lukoil traian vuia",
      "electromontaj nord",
      "aviatia utilitara",
      "aeroport nord",
      "traian vuia nord",
      "planoarelor",
      "vlad tepes",
      "camin someseni",
      "expo transilvania",
      "aurel vlaicu",
      "arte plastice",
      "crinului",
      "somes",
      "constanta",
      "sora",
      "central",
      "closca",
      "piata garii sud"
    ])
  },
  {
    "number": "4",
    "direction": "tur",
    "stations": toIds([
      "disp. ira",
      "expo transilvania",
      "aurel vlaicu",
      "arte plastice",
      "crinului",
      "somes",
      "constanta",
      "sora",
      "central",
      "closca",
      "piata garii"
    ])
  },
  {
    "number": "4",
    "direction": "retur",
    "stations": toIds([
      "piata garii sud",
      "traian",
      "i. p. voitesti",
      "regionala cfr",
      "biserica sf. petru",
      "piata marasti",
      "maresal c-tin. prezan",
      "siretului",
      "pod someseni"
    ])
  },
  {
    "number": "3",
    "direction": "tur",
    "stations": toIds([
      "snagov nord",
      "borsec nord",
      "bistritei",
      "septimiu albini nord",
      "piata cipariu nord",
      "piata avram iancu",
      "sora",
      "central",
      "closca",
      "piata garii"
    ])
  },
  {
    "number": "3",
    "direction": "retur",
    "stations": toIds([
      "piata garii sud",
      "traian",
      "i. p. voitesti sud",
      "teatru",
      "piata cipariu est",
      "septimiu albini sud",
      "nicolae titulescu",
      "herculane",
      "borsec sud",
      "snagov sud"
    ])
  },
  {
    "number": "2",
    "direction": "tur",
    "stations": toIds([
      "izlazului",
      "calea manastur",
      "agronomia",
      "calea motilor",
      "memorandumului sud",
      "central",
      "closca",
      "piata garii"
    ])
  },
  {
    "number": "2",
    "direction": "retur",
    "stations": toIds([
      "piata garii",
      "traian",
      "pod traian",
      "memorandumului nord",
      "spitalul de copii",
      "fabrica de bere",
      "gradini manastur",
      "ion mester"
    ])
  },
  {
    "number": "1",
    "direction": "tur",
    "stations": toIds([
      "disp. bucium",
      "primaverii",
      "minerva",
      "izlazului",
      "calea manastur",
      "agronomia",
      "calea motilor",
      "memorandumului sud",
      "victoria",
      "regionala cfr",
      "ploiesti",
      "paris",
      "piata 1 mai"
    ])
  },
  {
    "number": "1",
    "direction": "retur",
    "stations": toIds([
      "piata 1 mai",
      "barbu patriciu",
      "anton pann",
      "pod traian",
      "memorandumului nord",
      "spitalul de copii",
      "fabrica de bere",
      "gradini manastur",
      "ion mester",
      "peana",
      "garbau"
    ])
  },
  {
    "number": "50d",
    "direction": "tur",
    "stations": toIds([
      "zorilor",
      "spitalul recuperare sud",
      "observatorului sud",
      "gheorghe doja",
      "piata cipariu nord",
      "piata avram iancu",
      "piata mihai viteazul est",
      "piata abator",
      "paris",
      "rasaritului",
      "halta marasti",
      "bobalnei est",
      "terapia est",
      "terapia sud",
      "sinterom sud",
      "sieta",
      "termorom sud",
      "ers cug sud",
      "voronet 40",
      "oleandrului 32",
      "panselutelor 9"
    ])
  },
  {
    "number": "50d",
    "direction": "retur",
    "stations": toIds([
      "panselutelor 9",
      "narciselor 19",
      "voronet 85",
      "voronet 24",
      "unimet nord",
      "ers cug nord",
      "termorom nord",
      "sinterom nord",
      "terapia nord",
      "terapia vest",
      "bobalnei vest",
      "campul painii",
      "piata 1 mai sosire",
      "barbu patriciu",
      "anton pann",
      "i. p. voitesti",
      "teatru",
      "silviu dragomir",
      "observatorului nord",
      "spitalul recuperare nord",
      "gheorghe dima",
      "disp. zorilor"
    ])
  },
  {
    "number": "39c",
    "direction": "tur",
    "stations": toIds([
      "vama chinteni",
      "cluj innovation park"
    ])
  },
  {
    "number": "39c",
    "direction": "retur",
    "stations": toIds([
      "cluj innovation park",
      "vama chinteni"
    ])
  }
];

console.log(`About to insert ${linesToInsert.length} lines.`);

db.lines.insertMany(linesToInsert);

console.log("done. check above for any '⚠️' warnings before trusting the data.");